PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirm_password' in 'field list' in C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\PDO\Statement.php:55
Stack trace:
#0 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\PDO\Statement.php(55): PDOStatement->execute()
#1 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(882): Doctrine\DBAL\Driver\PDO\Statement->execute()
#2 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(518): Doctrine\DBAL\Connection->executeStatement('INSERT INTO use...', Array, Array)
#3 C:\laragon\www\Lab\app\Model.php(87): Doctrine\DBAL\Connection->insert('users', Array)
#4 C:\laragon\www\Lab\app\Controllers\Auth\AuthController.php(100): App\Model->insert(Array)
#5 [internal function]: App\Controllers\Auth\AuthController->register()
#6 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(482): call_user_func_array(Array, Array)
#7 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(440): Bramus\Router\Router->invoke('App\\Controllers...', Array)
#8 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(287): Bramus\Router\Router->handle(Array, true)
#9 C:\laragon\www\Lab\routers\index.php(11): Bramus\Router\Router->run()
#10 C:\laragon\www\Lab\index.php(7): require('C:\\laragon\\www\\...')
#11 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirm_password' in 'field list' in C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\PDO\Exception.php:24
Stack trace:
#0 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\PDO\Statement.php(57): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(882): Doctrine\DBAL\Driver\PDO\Statement->execute()
#2 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(518): Doctrine\DBAL\Connection->executeStatement('INSERT INTO use...', Array, Array)
#3 C:\laragon\www\Lab\app\Model.php(87): Doctrine\DBAL\Connection->insert('users', Array)
#4 C:\laragon\www\Lab\app\Controllers\Auth\AuthController.php(100): App\Model->insert(Array)
#5 [internal function]: App\Controllers\Auth\AuthController->register()
#6 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(482): call_user_func_array(Array, Array)
#7 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(440): Bramus\Router\Router->invoke('App\\Controllers...', Array)
#8 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(287): Bramus\Router\Router->handle(Array, true)
#9 C:\laragon\www\Lab\routers\index.php(11): Bramus\Router\Router->run()
#10 C:\laragon\www\Lab\index.php(7): require('C:\\laragon\\www\\...')
#11 {main}

Next Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirm_password' in 'field list' in C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php:52
Stack trace:
#0 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(1414): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#1 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(1356): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#2 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(888): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'INSERT INTO use...', Array, Array)
#3 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(518): Doctrine\DBAL\Connection->executeStatement('INSERT INTO use...', Array, Array)
#4 C:\laragon\www\Lab\app\Model.php(87): Doctrine\DBAL\Connection->insert('users', Array)
#5 C:\laragon\www\Lab\app\Controllers\Auth\AuthController.php(100): App\Model->insert(Array)
#6 [internal function]: App\Controllers\Auth\AuthController->register()
#7 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(482): call_user_func_array(Array, Array)
#8 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(440): Bramus\Router\Router->invoke('App\\Controllers...', Array)
#9 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(287): Bramus\Router\Router->handle(Array, true)
#10 C:\laragon\www\Lab\routers\index.php(11): Bramus\Router\Router->run()
#11 C:\laragon\www\Lab\index.php(7): require('C:\\laragon\\www\\...')
#12 {main}PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirm_password' in 'field list' in C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\PDO\Statement.php:55
Stack trace:
#0 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\PDO\Statement.php(55): PDOStatement->execute()
#1 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(882): Doctrine\DBAL\Driver\PDO\Statement->execute()
#2 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(518): Doctrine\DBAL\Connection->executeStatement('INSERT INTO use...', Array, Array)
#3 C:\laragon\www\Lab\app\Model.php(87): Doctrine\DBAL\Connection->insert('users', Array)
#4 C:\laragon\www\Lab\app\Controllers\Auth\AuthController.php(100): App\Model->insert(Array)
#5 [internal function]: App\Controllers\Auth\AuthController->register()
#6 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(482): call_user_func_array(Array, Array)
#7 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(440): Bramus\Router\Router->invoke('App\\Controllers...', Array)
#8 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(287): Bramus\Router\Router->handle(Array, true)
#9 C:\laragon\www\Lab\routers\index.php(11): Bramus\Router\Router->run()
#10 C:\laragon\www\Lab\index.php(7): require('C:\\laragon\\www\\...')
#11 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirm_password' in 'field list' in C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\PDO\Exception.php:24
Stack trace:
#0 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\PDO\Statement.php(57): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(882): Doctrine\DBAL\Driver\PDO\Statement->execute()
#2 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(518): Doctrine\DBAL\Connection->executeStatement('INSERT INTO use...', Array, Array)
#3 C:\laragon\www\Lab\app\Model.php(87): Doctrine\DBAL\Connection->insert('users', Array)
#4 C:\laragon\www\Lab\app\Controllers\Auth\AuthController.php(100): App\Model->insert(Array)
#5 [internal function]: App\Controllers\Auth\AuthController->register()
#6 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(482): call_user_func_array(Array, Array)
#7 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(440): Bramus\Router\Router->invoke('App\\Controllers...', Array)
#8 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(287): Bramus\Router\Router->handle(Array, true)
#9 C:\laragon\www\Lab\routers\index.php(11): Bramus\Router\Router->run()
#10 C:\laragon\www\Lab\index.php(7): require('C:\\laragon\\www\\...')
#11 {main}

Next Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirm_password' in 'field list' in C:\laragon\www\Lab\vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php:52
Stack trace:
#0 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(1414): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#1 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(1356): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#2 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(888): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'INSERT INTO use...', Array, Array)
#3 C:\laragon\www\Lab\vendor\doctrine\dbal\src\Connection.php(518): Doctrine\DBAL\Connection->executeStatement('INSERT INTO use...', Array, Array)
#4 C:\laragon\www\Lab\app\Model.php(87): Doctrine\DBAL\Connection->insert('users', Array)
#5 C:\laragon\www\Lab\app\Controllers\Auth\AuthController.php(100): App\Model->insert(Array)
#6 [internal function]: App\Controllers\Auth\AuthController->register()
#7 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(482): call_user_func_array(Array, Array)
#8 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(440): Bramus\Router\Router->invoke('App\\Controllers...', Array)
#9 C:\laragon\www\Lab\vendor\bramus\router\src\Bramus\Router\Router.php(287): Bramus\Router\Router->handle(Array, true)
#10 C:\laragon\www\Lab\routers\index.php(11): Bramus\Router\Router->run()
#11 C:\laragon\www\Lab\index.php(7): require('C:\\laragon\\www\\...')
#12 {main}